//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Partiel.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db2019EventsStudentEntities : DbContext
    {
        public Db2019EventsStudentEntities()
            : base("name=Db2019EventsStudentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Association> Associations { get; set; }
        public virtual DbSet<Drink> Drinks { get; set; }
        public virtual DbSet<DrinkType> DrinkTypes { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Participation> Participations { get; set; }
        public virtual DbSet<Path> Paths { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Stop> Stops { get; set; }
    }
}
